services:
  app:
    image: rbac-demo-with-express:latest
    container_name: rbac-demo-with-express
    restart: unless-stopped
    network_mode: host
    environment:
      - NODE_ENV=production
    volumes:
      - ./.env.production:/app/.env.production:ro
