name: RBAC Demo Backend Deployment

on:
  push:
    branches: [main]

env:
  PROJECT_NAME: rbac-demo-with-express
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  SERVER_PASS: ${{ secrets.SERVER_PASS }}
  APP_ENV: ${{ secrets.APP_ENV }}
  NODE_ENV: production
  EXTERNAL_PORT: ${{ secrets.APP_PORT }}
  INTERNAL_PORT: 4000
  WORKDIR: /app

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ env.SSH_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
          config: |
            Host target
              HostName ${{ env.SERVER_IP }}
              User ${{ env.SSH_USER }}
              StrictHostKeyChecking no

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          platforms: linux/arm64

      - name: Build Node Docker image
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --file Dockerfile \
            --load \
            -t ${{ env.PROJECT_NAME }}:latest \
            --build-arg WORKDIR="${{ env.WORKDIR }}" \
            --build-arg NODE_ENV="${{ env.NODE_ENV }}" \
            --build-arg INTERNAL_PORT="${{ env.INTERNAL_PORT }}" \
            .

      - name: Save Docker image
        run: |
          docker save -o /tmp/${{ env.PROJECT_NAME }}-temp-app.tar ${{ env.PROJECT_NAME }}:latest

      - name: Deploy to server
        run: |
          scp /tmp/${{ env.PROJECT_NAME }}-temp-app.tar target:/tmp/${{ env.PROJECT_NAME }}-temp-app.tar

          ssh target "bash -s" << 'EOF'
            # Create password script for sudo
            echo '#!/bin/bash
            echo "${{ env.SERVER_PASS }}"' > /tmp/askpass.sh
            chmod +x /tmp/askpass.sh
            
            # Set environment variables
            export SUDO_ASKPASS=/tmp/askpass.sh
            export WORKDIR=${{ env.WORKDIR }}

            # Stop and remove existing container if it exists
            sudo -A docker rm -f ${{ env.PROJECT_NAME }} 2>/dev/null || true

            # Remove old image if it exists
            sudo -A docker rmi ${{ env.PROJECT_NAME }}:latest 2>/dev/null || true

            # Load Docker image
            sudo -A docker load -i /tmp/${{ env.PROJECT_NAME }}-temp-app.tar

            # Ensure network exists
            sudo -A docker network create ${{ env.PROJECT_NAME }}-network 2>/dev/null || true

            # Create environment file on server
            echo '${{ env.APP_ENV }}' > /tmp/${{ env.PROJECT_NAME }}.env.production

            # Run new node container
            sudo -A docker run -d \
              --name "${{ env.PROJECT_NAME }}" \
              --network "${{ env.PROJECT_NAME }}-network" \
              -p "${{ env.EXTERNAL_PORT }}:${{ env.INTERNAL_PORT }}" \
              -v /tmp/${{ env.PROJECT_NAME }}.env.production:${{ env.WORKDIR }}/.env.production \
              "${{ env.PROJECT_NAME }}:latest"

            # Clean up
            sudo -A rm -f /tmp/${{ env.PROJECT_NAME }}-temp-app.tar
            rm -f /tmp/${{ env.PROJECT_NAME }}.env.production
            rm -f /tmp/askpass.sh
          EOF
